services:
    db:
        extends:
            file: db/docker-compose.yml
            service: db

    db-api-controller:
        extends:
            file: db/docker-compose.yml
            service: db-api-controller
        volumes:
            - ./conf:/app/conf
            - ./databridging:/app/databridging

    adminer:
        extends:
            file: db/docker-compose.yml
            service: adminer

    web:
        ports:
            - 8080:8080
        build:
            context: ./web
        volumes:
            - ./conf:/web/conf
            - ./web:/web
            - ./resources:/web/resources
